FROM debian:10

MAINTAINER Ruslan Valovyi
ENV GIT_REPO el_garden

#Build Debian dependencies

RUN mkdir -p /opt/cross/air1
RUN mkdir -p /opt/cross/cross-pi-gcc-10.3.0-2
RUN mkdir -p /opt/cross/dir2

ARG DIR

RUN /bin/bash -c 'CROSS_DIR_LIST="$(ls /opt/cross)" \
    && for d in $CROSS_DIR_LIST; do \
          if [[ $d == cross-pi-gcc* ]] ; then \ 
              TOOLCHAIN_DIR_NAME=$d; break; \              
          fi; \
       done \
    && echo "export PATH=$PATH:/opt/cross/$TOOLCHAIN_DIR_NAME/bin:/opt/cross/$TOOLCHAIN_DIR_NAME/lib:/opt/cross/$TOOLCHAIN_DIR_NAME/include" >> ~/.bashrc \
    && echo "$TOOLCHAIN_DIR_NAME" > /tmp/temp_dir_name '

#ENV PATH "$PATH:/opt/cross/$TOOLCHAIN_DIR_NAME/bin:/opt/cross/$TOOLCHAIN_DIR_NAME/lib:/opt/cross/$TOOLCHAIN_DIR_NAME/include"

RUN . ~/.bashrc && echo "PATH: $PATH"

RUN rm -rf /tmp/*

