titles_en = {
 "LANG": "EN 🇬🇧 English",

 "TITLE_SYSTEM_STATE": "System state",
 "TITLE_SYSTEM_SETTINGS": "⚙System settings",
 "TITLE_LIGHT": "Lighting",
 "TITLE_PUMP": "Pump",
 "TITLE_PH": "pH",
 "TITLE_EC": "EC",
 "TITLE_DATE": "Date in the system",
 "TITLE_TIME": "System tume",
 "TITLE_LIGHT_ON": "Light switch on time",
 "TITLE_LIGHT_OFF": "Light switch off time",
 "TITLE_PUMP_ON": "Duration of pump on",
 "TITLE_PUMP_OFF": "Duration of pump off",
 "TITLE_PUMP_NIGHT": "Number of pump starts per night",
 "TITLE_ENTERED": "You entered",
 "TITLE_NEXT_LIGHT_ON": "The next lighting switch-on",
 "TITLE_NEXT_LIGHT_OFF": "The next lighting switch-off",
 "TITLE_NEXT_PUMP_ON": "The next pumping switch-on",
 "TITLE_NEXT_PUMP_OFF": "The next pumping switch-off",
 "TITLE_NORM": "Should be",

 "PROPOSE_MAIN": "Select an action",
 "PROPOSE_SETTINGS": "Select which parameter you want to configure",
 "PROPOSE_LIGHT_ON": "Enter the time when you want to turn on the light [0..23]",
 "PROPOSE_LIGHT_OFF": "Enter the time when you want to turn off the light [0..23]",
 "PROPOSE_PUMP_ON": "Enter how many minutes the pump should be on [5..60]",
 "PROPOSE_PUMP_OFF": "Enter how many minutes the pump should be off [5..60]",
 "PROPOSE_PUMP_NIGHT": "Enter the number of times you want to turn on the pump during the night [1..24]",
 "PROPOSE_LANG": "Select a language",

 "ASK_CONFIRMATION": "Do you confirm the data entered?",
 "ASK_SYS_SW_ON": "Do you want to turn on the system?",
 "ASK_SYS_SW_OFF": "Do you want to turn off the system?",

 "CONFIRM_YES": "Yes ✅",
 "CONFIRM_NO": "No ❌",

 "MESSAGE_CONFIG_CHANGED": "Configuration changed",
 "MESSAGE_MINUTES": "minutes",
 "MESSAGE_TIMES": "times",
 "MESSAGE_SYS_ALREADY_ON": "System is on",
 "MESSAGE_SYS_ALREADY_OFF": "System is off",

 "WARNING_INCORRECT_DATA": "⚠You entered incorrect data‼",
 "WARNING_CANCELLED": "⚠The 'Cancel' command is received‼",
 "WARNING_CONFIG_CHANGED": "⚠Error changing the configuration‼",
 "WARNING_CONFIG_CANCELLED": "⚠Configuration changes are canceled‼",

 "STATE_SYSTEM_ON": "The system is running ✅",
 "STATE_SYSTEM_OFF": "The system is stopped ❌",
 "STATE_ON": "Enabled ✅",
 "STATE_OFF": "Disabled ❌",

 "KEY_MAIN_DETAIL": "Details",
 "KEY_MAIN_SW_ON": "💡 Turn on the system",
 "KEY_MAIN_SW_OFF": "⏻ Turn off the system",
 "KEY_MAIN_SETTINGS": "⚙ Settings",

 "KEY_OPTION_LIGHT": "Lighting",
 "KEY_OPTION_PUMP": "Pumping",
 "KEY_OPTION_PH": "pH",
 "KEY_OPTION_EC": "EC",
 "KEY_OPTION_LANG": "Change language",
 "KEY_OPTION_BACK": "Cancel",

 "SYSTEM_FAILURE": "No connection to the system ❌",
 "SYSTEM_UNKNOWN_USER": "You do not have access to the 'Electronic garden' system",
}
